package framework.cli;
import java.util.Set;

import org.reflections.Reflections;

import annotations.SchemaEligible;
import framework.runtime.ObjectFactory;
import framework.runtime.ObjectRepository;
import framework.runtime.ObjectViewer;
import framework.schema.SchemaRegistry; 
import framework.schema.SchemaValidator;

/**
 * All javadoc generated by AI and edited where needed. 
 * Entry point for the schema-driven runtime framework.
 * <p>
 * This class is responsible for:
 * <ul>
 *   <li>Discovering schema-eligible domain classes via reflection</li>
 *   <li>Initializing core framework components</li>
 *   <li>Launching the CLI controller</li>
 * </ul>
 * All runtime behavior is delegated to {@link CLIController}.
 */

public class Main {
    
    /**
     * Launches the framework CLI.
     *
     * @param args command-line arguments (unused)
     */

    public static void main(String[] args) {
        Reflections domainScan = new Reflections("domain");
        Set<Class<?>> classes = domainScan.getTypesAnnotatedWith(SchemaEligible.class);
        SchemaRegistry registry = new SchemaRegistry(classes);
        ObjectRepository repository = new ObjectRepository(); 
        SchemaValidator validator = new SchemaValidator(registry, repository); 
        ObjectFactory factory = new ObjectFactory(registry, repository); 
        ObjectViewer viewer = new ObjectViewer(repository); 
        CLIController controller = new CLIController(registry, validator, factory, repository, viewer); 
    }
}


